version: '3.7'
services:
    nodejs-mywhats:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: "node:14-slim"
        container_name: nodejs-mywhats
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app